name: 🚀 publish apllication

on:
  push:
    branches:
    - main

jobs:
  publish:
    runs-on: 'ubuntu-latest'  
    steps:
    - name: 📂 Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: 🛠️ Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: 🔑 Log in to registry
      uses: docker/login-action@v2
      with:
        registry:  ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    # - name: 🔖 Get release tag name
    #   id: get_release
    #   uses: cardinalby/git-get-release-action@v1
    #   env:
    #     GITHUB_TOKEN: ${{ github.token }}
    #   with:
    #     # latest: false
    #     tag: 'v1.0.0'    
    #     prerelease: true



    - name: 🔖 Set fake release tag name
      run: echo "FAKE_RELEASE_TAG=v0.0.1" >> "$GITHUB_ENV"
  
    - name: 🔄 downcase REPO
      uses: ASzc/change-string-case-action@v1
      id: downcase
      with:
          string: ${{ github.repository }}

    - name: ♻️ Set correct environment
      run: |
        # TAG=${{ steps.get_release.outputs.tag_name }}
        TAG=${{ env.FAKE_RELEASE_TAG }}
        echo "TAG=$TAG" >> "$GITHUB_ENV"
        REPO=${{ steps.downcase.outputs.lowercase }}
        echo "REPO=$REPO" >> "$GITHUB_ENV"

    - name: 🐳 Docker metadata
      id: docker_meta
      uses: docker/metadata-action@v5
      with:
        images: ghcr.io/${{ env.REPO }}-${{ matrix.directory}}
        tags: |
          type=semver,pattern={{major}}.{{minor}}.{{patch}},value=${{ env.TAG }}
          type=semver,pattern={{major}}.{{minor}},value=${{ env.TAG }}
          type=semver,pattern={{major}},value=${{ env.TAG }}
 
    - name: 🏗️ Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: ghcr.io/${{ env.REPO }}/my-fullstack-project:${{ env.TAG }}
        # tags: ghcr.io/${{ env.REPO }}/my-fullstack-project:${{ github.sha }}
        labels: ${{ steps.docker_meta.outputs.labels }}
        file: ./Dockerfile
        build-args: |
          REACT_APP_SERVER_PATH=${{ env.REACT_APP_SERVER_PATH }}
          REACT_APP_VOLUME_NAME=${{ env.REACT_APP_VOLUME_NAME }}

    - name: Log in to Azure
      uses: azure/login@v1
      with:
       creds: ${{ secrets.AZURE_CREDENTIALS }}
        
    
    # - name: Build and deploy Container App
    #   uses: azure/container-apps-deploy-action@v1
    #   with:
    #     resourceGroup: gh-action-app-7117113225-2-rg
    #     containerAppName: full-stack-project 
    #     imageToDeploy: 'ghcr.io/${{ env.REPO }}-my-fullstack-project:${{ github.sha }}'
    #     registryUrl: ghcr.io
    #     registryUsername: ${{ github.actor }}
    #     registryPassword: ${{ secrets.GITHUB_TOKEN }}
        # containerOsType: 'Linux'  
        # 
    # - name: Build and push container image to registry
    #   uses: azure/container-apps-deploy-action@v2
    #   with:
    #     registryUrl: ghcr.io
    #     registryUsername: ${{ github.actor }}
    #     registryPassword: ${{ secrets.GITHUB_TOKEN }}
    #     containerAppName: my-container-app
    #     resourceGroup: NetworkWatcherRG

    #     # imageToDeploy: ghcr.io/${{ env.REPO }}/my-fullstack-project:${{ github.sha }}
    #     imageToDeploy: ghcr.io/${{ env.REPO }}/my-fullstack-project:${{ env.TAG }}

  


   