name: Trigger auto deployment for my-container-app1

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ feature ]
    paths:
    - '**'
    - '.github/workflows/my-container-app1-AutoDeployTrigger-37a3d78e-c2e4-4f3f-a761-0fbd65890891.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.MYCONTAINERAPP1_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: ghcr.io
          registryUsername: ${{ secrets.MYCONTAINERAPP1_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.MYCONTAINERAPP1_REGISTRY_PASSWORD }}
          containerAppName: my-container-app1
          resourceGroup: NetworkWatcherRG
          imageToBuild: ghcr.io/docker pull ghcr.io/leahlandau/fullstackaplicationlali-my-fullstack-project:${{ github.sha }}
          
            

     

