name: Trigger auto deployment for tuesday

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ feature ]
    paths:
    - '**'
    - '.github/workflows/tuesday-AutoDeployTrigger-359fdd95-c043-4989-be30-95354f03df79.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.TUESDAY_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: ghcr.io
          registryUsername: ${{ secrets.TUESDAY_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.TUESDAY_REGISTRY_PASSWORD }}
          containerAppName: tuesday
          resourceGroup: NetworkWatcherRG
          imageToBuild: ghcr.io/tuesday:${{ github.sha }}
          

     

